spring:
  application:
    name: localizationAPI
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true