spring:
  application:
    name: localizationAPI
  datasource:
    url: jdbc:mysql://localhost:3306/localization_api
    username: root
    password: Spanis@123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true